=== bartongroup/FM_FunPDBe/funpdbe_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "https://github.com/funpdbe-consortium/funpdbe_schema/blob/master/funpdbe_schema.v0.0.1.json",
  "title": "funpdbe_schema",
  "type": "object",
  "properties": {
    "data_resource": {
      "type": "string",
      "description": "Name of the database or software"
    },
    "resource_version": {
      "type": "string",
      "description": "Version of the resource"
    },
    "software_version": {
      "type": "string",
      "description": "Version of the software used"
    },
    "resource_entry_url": {
      "type": "string",
      "description": "URL linking to the entry at the partner resource"
    },
    "release_date": {
      "type": "string",
      "description": "Release date of the annotation",
      "pattern": "^[0-3]*[0-9]/[0-1]*[0-9]/[1-2][0-9]{3}$"
    },
    "pdb_id": {
      "type": "string",
      "description": "PDB identifier",
      "pattern": "^[1-9][a-zA-Z0-9]{3}$"
    },
    "additional_entry_annotations": {
      "type": "object",
      "description": "Additional entry-level annotations"
    },
    "chains": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "chain_label": {
            "type": "string",
            "description": "PDB chain identifier"
          },
          "additional_chain_annotations": {
            "type": "object",
            "description": "Additional chain-level annotations"
          },
          "residues": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "pdb_res_label": {
                  "type": "string",
                  "description": "Residue index from the related PDB entry"
                },
                "aa_type": {
                  "type": "string",
                  "description": "Three-letter amino acid code",
                  "pattern": "^[A-Za-z0-9]+$"
                },
                "additional_residue_annotations": {
                  "type": "object",
                  "description": "Additional residue-level annotations"
                },
                "site_data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "site_id_ref": {
                        "type": "integer",
                        "description": "Reference to site_id"
                      },
                      "raw_score": {
                        "type": "number",
                        "description": "Raw calculated score"
                      },
                      "confidence_score": {
                        "type": "number",
                        "description": "Confidence level of the annotation (0-1)",
                        "minimum": 0.0,
                        "maximum": 1.0
                      },
                      "confidence_classification": {
                        "type": "string",
                        "description": "Confidence classification of the residue",
                        "enum": [
                          "high",
                          "medium",
                          "low",
                          "null"
                        ]
                      }
                    },
                    "required": [
                      "site_id_ref",
                      "raw_score",
                      "confidence_score",
                      "confidence_classification"
                    ],
                    "additionalProperties": false
                  },
                  "minItems": 1,
                  "uniqueItems": true
                }
              },
              "required": [
                "pdb_res_label",
                "aa_type",
                "site_data"
              ],
              "additionalProperties": false
            },
            "minItems": 1,
            "uniqueItems": true
          }
        },
        "required": [
          "chain_label",
          "residues"
        ],
        "additionalProperties": false
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "sites": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "site_id": {
            "type": "integer",
            "description": "Site identifier"
          },
          "label": {
            "type": "string",
            "description": "Site label"
          },
          "source_database": {
            "type": "string",
            "description": "Name of the source database"
          },
          "source_accession": {
            "type": "string",
            "description": "Accession identifier"
          },
          "source_release_date": {
            "type": "string",
            "description": "Date of acquiring data from source",
            "pattern": "^[0-3]*[0-9]/[0-1]*[0-9]/[1-2][0-9]{3}$"
          },
          "additional_site_annotations": {
            "type": "object",
            "description": "Additional site-level annotations"
          }
        },
        "required": [
          "site_id",
          "label"
        ],
        "additionalProperties": false
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "evidence_code_ontology": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "eco_term": {
            "type": "string",
            "description": "Evidence Code Ontology (ECO) term - http://www.evidenceontology.org/"
          },
          "eco_code": {
            "type": "string",
            "description": "Evidence Code Ontology (ECO) code - http://www.evidenceontology.org/",
            "pattern": "^ECO_[0-9]{7}$"
          }
        },
        "required": [
          "eco_code"
        ],
        "additionalProperties": false
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": [
    "data_resource",
    "pdb_id",
    "chains",
    "evidence_code_ontology",
    "sites"
  ],
  "additionalProperties": false
}

=== bartongroup/FM_FunPDBe/tests/mock_data.json
{
    "pdb_id": "2aqa",
    "data_resource": "cath-funsites",
    "resource_version": "1.0.0",
    "software_version": "1.0.0",
    "resource_entry_url": "https://example.com/foo/bar",
    "release_date": "01/01/2000",
    "chains": [
        {
            "chain_label": "A",
            "residues": [
                {
                    "pdb_res_label": "2",
                    "aa_type": "HIS",
                    "site_data": [
                        {
                            "site_id_ref": 1,
                            "raw_score": 0.7,
                            "confidence_score": 0.9,
                            "confidence_classification": "high"
                        }
                    ]
                }
            ]
        }
    ],
    "sites": [
        {
            "site_id": 1,
            "label": "ligand_binding_site",
            "source_database": "pdb",
            "source_accession": "1abc",
            "source_release_date": "01/01/2000"
        }
    ],
    "evidence_code_ontology": [
        {
            "eco_term": "manually_curated",
            "eco_code": "ECO_0000042"
        }
    ]
}
